version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: civicconnect
      POSTGRES_PASSWORD: civicconnect
      POSTGRES_DB: civicconnect
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./api
    command: npm run dev
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_USER: civicconnect
      DB_PASSWORD: civicconnect
      DB_NAME: civicconnect
      DB_PORT: 5432
    depends_on:
      - db

  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  postgres_data:
